## Homework#2

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import math
from patsy import dmatrices


import statsmodels.discrete.discrete_model as sm
import statsmodels.formula.api as smf
from statsmodels.graphics.regressionplots import *
from sklearn import datasets, linear_model
from sklearn.metrics import confusion_matrix

In [37]:
Default = pd.read_csv('data/Default.csv', header=0)

In [38]:
Default.head()

  default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [39]:
y, X = dmatrices('default~income+balance', Default, return_type = 'dataframe')
print (y)

      default[No]  default[Yes]
0             1.0           0.0
1             1.0           0.0
2             1.0           0.0
3             1.0           0.0
4             1.0           0.0
5             1.0           0.0
6             1.0           0.0
7             1.0           0.0
8             1.0           0.0
9             1.0           0.0
10            1.0           0.0
11            1.0           0.0
12            1.0           0.0
13            1.0           0.0
14            1.0           0.0
15            1.0           0.0
16            1.0           0.0
17            1.0           0.0
18            1.0           0.0
19            1.0           0.0
20            1.0           0.0
21            1.0           0.0
22            1.0           0.0
23            1.0           0.0
24            1.0           0.0
25            1.0           0.0
26            1.0           0.0
27            1.0           0.0
28            1.0           0.0
29            1.0           0.0
...           ...           ...
9970          1.0           0.0
9971          1.0           0.0
9972          1.0           0.0
9973          1.0           0.0
9974          1.0           0.0
9975          1.0           0.0
9976          1.0           0.0
9977          1.0           0.0
9978          0.0           1.0
9979          1.0           0.0
9980          1.0           0.0
9981          1.0           0.0
9982          1.0           0.0
9983          1.0           0.0
9984          1.0           0.0
9985          1.0           0.0
9986          1.0           0.0
9987          1.0           0.0
9988          1.0           0.0
9989          1.0           0.0
9990          1.0           0.0
9991          1.0           0.0
9992          1.0           0.0
9993          1.0           0.0
9994          1.0           0.0
9995          1.0           0.0
9996          1.0           0.0
9997          1.0           0.0
9998          1.0           0.0
9999          1.0           0.0

[10000 rows x 2 columns]

In [40]:
print(X)

      Intercept        income      balance
0           1.0  44361.625074   729.526495
1           1.0  12106.134700   817.180407
2           1.0  31767.138947  1073.549164
3           1.0  35704.493935   529.250605
4           1.0  38463.495879   785.655883
5           1.0   7491.558572   919.588530
6           1.0  24905.226578   825.513331
7           1.0  17600.451344   808.667504
8           1.0  37468.529288  1161.057854
9           1.0  29275.268293     0.000000
10          1.0  21871.073089     0.000000
11          1.0  13268.562221  1220.583753
12          1.0  28251.695345   237.045114
13          1.0  44994.555849   606.742343
14          1.0  23810.174050  1112.968401
15          1.0  45042.413036   286.232560
16          1.0  50265.312354     0.000000
17          1.0  17636.539617   527.540184
18          1.0  61566.106118   485.936864
19          1.0  26464.631389  1095.072735
20          1.0  50500.182198   228.952550
21          1.0  32457.509075   954.261793
22          1.0  51317.883082  1055.956605
23          1.0  30466.103257   641.984389
24          1.0  34353.314305   773.211725
25          1.0  25211.332161   855.008523
26          1.0  41473.511801   642.999739
27          1.0  32189.094952  1454.863272
28          1.0  39376.394619   615.704277
29          1.0  16556.070205  1119.569353
...         ...           ...          ...
9970        1.0  25687.326050  1294.500408
9971        1.0  20975.560495   180.620128
9972        1.0  14455.865365   755.432801
9973        1.0  37668.366788   876.119027
9974        1.0  26051.398320   933.332025
9975        1.0  21287.942487   908.315934
9976        1.0  25401.133121   218.417559
9977        1.0  16624.339111   915.439827
9978        1.0  47287.257108  2202.462395
9979        1.0  30697.245062   173.249172
9980        1.0  13684.789952   770.015741
9981        1.0  40656.951448   739.418018
9982        1.0  59441.309981   623.526119
9983        1.0  49861.003411   506.625454
9984        1.0  52861.744197   875.241640
9985        1.0  39957.127855   842.949429
9986        1.0  15332.017833   401.332674
9987        1.0  45479.466985  1092.906583
9988        1.0  41740.686597     0.000000
9989        1.0  20013.350644   999.281112
9990        1.0  25374.899085   372.379239
9991        1.0  54802.078221   658.799558
9992        1.0  45490.682463  1111.647317
9993        1.0  56633.448744   938.836241
9994        1.0  14955.941689   172.412987
9995        1.0  52992.378914   711.555020
9996        1.0  19660.721768   757.962918
9997        1.0  58636.156984   845.411989
9998        1.0  36669.112365  1569.009053
9999        1.0  16862.952321   200.922183

[10000 rows x 3 columns]

## Question(a)

In [41]:
logit = sm.Logit(y.iloc[:,1], X)
print(logit.fit().summary())

Optimization terminated successfully.
         Current function value: 0.078948
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:           default[Yes]   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Sat, 20 Oct 2018   Pseudo R-squ.:                  0.4594
Time:                        18:48:00   Log-Likelihood:                -789.48
converged:                       True   LL-Null:                       -1460.3
                                        LLR p-value:                4.541e-292
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -11.5405      0.435    -26.544      0.000     -12.393     -10.688
income      2.081e-05   4.99e-06      4.174      0.000     1.1e-05    3.06e-05
balance        0.0056      0.000     24.835      0.000       0.005       0.006
==============================================================================

Possibly complete quasi-separation: A fraction 0.14 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [42]:
logit.fit().predict()

Optimization terminated successfully.
         Current function value: 0.078948
         Iterations 10

array([1.50472802e-03, 1.26192994e-03, 8.02621054e-03, ...,
       3.88716068e-03, 1.28189088e-01, 4.29711151e-05])

In [43]:
predict_label = pd.DataFrame(np.zeros(shape=(10000,1)), columns = ['label'])

In [44]:
predict_label.iloc[logit.fit().predict()>0.5] = 1
# this works also: predict_label[logit.fit().predict()>0.5] = 1

Optimization terminated successfully.
         Current function value: 0.078948
         Iterations 10

In [45]:
print(predict_label)

      label
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
...     ...
9970    0.0
9971    0.0
9972    0.0
9973    0.0
9974    0.0
9975    0.0
9976    0.0
9977    0.0
9978    1.0
9979    0.0
9980    0.0
9981    0.0
9982    0.0
9983    0.0
9984    0.0
9985    0.0
9986    0.0
9987    0.0
9988    0.0
9989    0.0
9990    0.0
9991    0.0
9992    0.0
9993    0.0
9994    0.0
9995    0.0
9996    0.0
9997    0.0
9998    0.0
9999    0.0

[10000 rows x 1 columns]

In [46]:
confusion_matrix(y.iloc[:,1], predict_label.iloc[:,0])

array([[9629,   38],
       [ 225,  108]], dtype=int64)

In [47]:
y_actu = pd.Series(y.iloc[:,1], name='Actual')
y_pred = pd.Series(predict_label.iloc[:,0], name='Predicted')
df_confusion = pd.crosstab(y_actu, y_pred)
print(df_confusion)

Predicted   0.0  1.0
Actual
0.0        9629   38
1.0         225  108

In [48]:
np.mean(y.iloc[:,1] == predict_label.iloc[:,0]) # to get accuracy

0.9737

## Question(b)

In [49]:
Default_train = Default[Default.index < 7000]
Default_test = Default[Default.index >= 7000]

In [50]:
Default_train

     default student      balance        income
0         No      No   729.526495  44361.625074
1         No     Yes   817.180407  12106.134700
2         No      No  1073.549164  31767.138947
3         No      No   529.250605  35704.493935
4         No      No   785.655883  38463.495879
5         No     Yes   919.588530   7491.558572
6         No      No   825.513331  24905.226578
7         No     Yes   808.667504  17600.451344
8         No      No  1161.057854  37468.529288
9         No      No     0.000000  29275.268293
10        No     Yes     0.000000  21871.073089
11        No     Yes  1220.583753  13268.562221
12        No      No   237.045114  28251.695345
13        No      No   606.742343  44994.555849
14        No      No  1112.968401  23810.174050
15        No      No   286.232560  45042.413036
16        No      No     0.000000  50265.312354
17        No     Yes   527.540184  17636.539617
18        No      No   485.936864  61566.106118
19        No      No  1095.072735  26464.631389
20        No      No   228.952550  50500.182198
21        No      No   954.261793  32457.509075
22        No      No  1055.956605  51317.883082
23        No      No   641.984389  30466.103257
24        No      No   773.211725  34353.314305
25        No      No   855.008523  25211.332161
26        No      No   642.999739  41473.511801
27        No      No  1454.863272  32189.094952
28        No      No   615.704277  39376.394619
29        No     Yes  1119.569353  16556.070205
...      ...     ...          ...           ...
6970      No      No     0.000000  36581.803899
6971      No      No   594.601261  36190.756388
6972      No     Yes   875.712944  18696.953577
6973      No      No   949.314977  50404.278761
6974      No      No   252.376727  39723.483731
6975      No      No  1162.567975  21753.528346
6976      No     Yes  1244.359563  19232.047439
6977      No      No   578.495565  46030.881277
6978      No      No   443.900953  50768.444874
6979      No      No  1316.089253  41314.169522
6980      No      No   904.424081  56062.016531
6981      No     Yes  1037.974595  15580.768879
6982      No      No   842.985665  42682.142013
6983      No     Yes  1258.528735  10920.964585
6984      No     Yes   297.390738  19383.791147
6985     Yes     Yes  1553.349657  18091.943736
6986      No     Yes   684.935381  21908.571587
6987      No      No  1265.501264  32910.397437
6988      No      No   362.611151  39296.077993
6989      No      No  1532.916209  22080.921771
6990      No     Yes  1341.615739  26319.015588
6991      No     Yes  1086.161108  23576.786730
6992      No      No   496.001763  32818.157065
6993      No      No  1597.052084  50827.807538
6994      No     Yes  2092.458530  14514.769959
6995      No     Yes  1019.984293  23795.422476
6996      No      No   765.233878  29096.417261
6997      No      No   928.964970  46709.480276
6998      No     Yes  1787.201938  17553.607249
6999      No      No   628.136804  38436.191452

[7000 rows x 4 columns]

In [51]:
Default_train.shape

(7000, 4)

In [52]:
Default_test.shape

(3000, 4)

In [53]:
y_train, X_train = dmatrices('default~income+balance', Default_train, return_type = 'dataframe')
y_test, X_test = dmatrices('default~income+balance', Default_test, return_type = 'dataframe')

In [54]:
logit = sm.Logit(y_train.iloc[:,1], X_train)
print (logit.fit().summary())

Optimization terminated successfully.
         Current function value: 0.079606
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:           default[Yes]   No. Observations:                 7000
Model:                          Logit   Df Residuals:                     6997
Method:                           MLE   Df Model:                            2
Date:                Sat, 20 Oct 2018   Pseudo R-squ.:                  0.4669
Time:                        18:48:01   Log-Likelihood:                -557.24
converged:                       True   LL-Null:                       -1045.4
                                        LLR p-value:                1.024e-212
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -11.6742      0.521    -22.408      0.000     -12.695     -10.653
income      2.253e-05   5.95e-06      3.787      0.000    1.09e-05    3.42e-05
balance        0.0057      0.000     21.105      0.000       0.005       0.006
==============================================================================

Possibly complete quasi-separation: A fraction 0.15 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [55]:
preds = logit.fit().predict(X_test)
predict_label = pd.DataFrame(np.zeros(shape=(X_test.shape[0],1)), columns = ['label'])
threshold = 0.5
predict_label.iloc[preds.values > threshold] = 1  
confusion_matrix(y_test.iloc[:,1], predict_label.iloc[:,0])

Optimization terminated successfully.
         Current function value: 0.079606
         Iterations 10

array([[2898,    9],
       [  61,   32]], dtype=int64)

In [56]:
1-np.mean(y_test.iloc[:,1].values==predict_label.iloc[:,0].values) # to get accuracy

0.023333333333333317

## Question (c)

In [57]:
y_train, X_train = dmatrices('default~income+balance+student', Default_train, return_type = 'dataframe')
y_test, X_test = dmatrices('default~income+balance+student', Default_test, return_type = 'dataframe')

In [58]:
X_train

      Intercept  student[T.Yes]        income      balance
0           1.0             0.0  44361.625074   729.526495
1           1.0             1.0  12106.134700   817.180407
2           1.0             0.0  31767.138947  1073.549164
3           1.0             0.0  35704.493935   529.250605
4           1.0             0.0  38463.495879   785.655883
5           1.0             1.0   7491.558572   919.588530
6           1.0             0.0  24905.226578   825.513331
7           1.0             1.0  17600.451344   808.667504
8           1.0             0.0  37468.529288  1161.057854
9           1.0             0.0  29275.268293     0.000000
10          1.0             1.0  21871.073089     0.000000
11          1.0             1.0  13268.562221  1220.583753
12          1.0             0.0  28251.695345   237.045114
13          1.0             0.0  44994.555849   606.742343
14          1.0             0.0  23810.174050  1112.968401
15          1.0             0.0  45042.413036   286.232560
16          1.0             0.0  50265.312354     0.000000
17          1.0             1.0  17636.539617   527.540184
18          1.0             0.0  61566.106118   485.936864
19          1.0             0.0  26464.631389  1095.072735
20          1.0             0.0  50500.182198   228.952550
21          1.0             0.0  32457.509075   954.261793
22          1.0             0.0  51317.883082  1055.956605
23          1.0             0.0  30466.103257   641.984389
24          1.0             0.0  34353.314305   773.211725
25          1.0             0.0  25211.332161   855.008523
26          1.0             0.0  41473.511801   642.999739
27          1.0             0.0  32189.094952  1454.863272
28          1.0             0.0  39376.394619   615.704277
29          1.0             1.0  16556.070205  1119.569353
...         ...             ...           ...          ...
6970        1.0             0.0  36581.803899     0.000000
6971        1.0             0.0  36190.756388   594.601261
6972        1.0             1.0  18696.953577   875.712944
6973        1.0             0.0  50404.278761   949.314977
6974        1.0             0.0  39723.483731   252.376727
6975        1.0             0.0  21753.528346  1162.567975
6976        1.0             1.0  19232.047439  1244.359563
6977        1.0             0.0  46030.881277   578.495565
6978        1.0             0.0  50768.444874   443.900953
6979        1.0             0.0  41314.169522  1316.089253
6980        1.0             0.0  56062.016531   904.424081
6981        1.0             1.0  15580.768879  1037.974595
6982        1.0             0.0  42682.142013   842.985665
6983        1.0             1.0  10920.964585  1258.528735
6984        1.0             1.0  19383.791147   297.390738
6985        1.0             1.0  18091.943736  1553.349657
6986        1.0             1.0  21908.571587   684.935381
6987        1.0             0.0  32910.397437  1265.501264
6988        1.0             0.0  39296.077993   362.611151
6989        1.0             0.0  22080.921771  1532.916209
6990        1.0             1.0  26319.015588  1341.615739
6991        1.0             1.0  23576.786730  1086.161108
6992        1.0             0.0  32818.157065   496.001763
6993        1.0             0.0  50827.807538  1597.052084
6994        1.0             1.0  14514.769959  2092.458530
6995        1.0             1.0  23795.422476  1019.984293
6996        1.0             0.0  29096.417261   765.233878
6997        1.0             0.0  46709.480276   928.964970
6998        1.0             1.0  17553.607249  1787.201938
6999        1.0             0.0  38436.191452   628.136804

[7000 rows x 4 columns]

In [59]:
logit = sm.Logit(y_train.iloc[:,1], X_train)
print (logit.fit().summary())

Optimization terminated successfully.
         Current function value: 0.079240
         Iterations 10
                           Logit Regression Results
==============================================================================
Dep. Variable:           default[Yes]   No. Observations:                 7000
Model:                          Logit   Df Residuals:                     6996
Method:                           MLE   Df Model:                            3
Date:                Sat, 20 Oct 2018   Pseudo R-squ.:                  0.4694
Time:                        18:48:01   Log-Likelihood:                -554.68
converged:                       True   LL-Null:                       -1045.4
                                        LLR p-value:                1.986e-212
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        -11.0147      0.589    -18.704      0.000     -12.169      -9.860
student[T.Yes]    -0.6464      0.285     -2.271      0.023      -1.204      -0.089
income          4.711e-06   9.88e-06      0.477      0.633   -1.46e-05    2.41e-05
balance            0.0058      0.000     20.957      0.000       0.005       0.006
==================================================================================

Possibly complete quasi-separation: A fraction 0.15 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [60]:
preds = logit.fit().predict(X_test)
predict_label = pd.DataFrame(np.zeros(shape=(X_test.shape[0],1)), columns = ['label'])
threshold = 0.5
predict_label.iloc[preds.values > threshold] = 1  
confusion_matrix(y_test.iloc[:,1], predict_label.iloc[:,0])

Optimization terminated successfully.
         Current function value: 0.079240
         Iterations 10

array([[2896,   11],
       [  61,   32]], dtype=int64)

In [61]:
1-np.mean(y_test.iloc[:,1].values==predict_label.iloc[:,0].values) # to get accuracy

0.02400000000000002

Including the student variable didn't help reduce the test error rate

## Question (d)

In [62]:
# refer to https://stackoverflow.com/questions/39163354/evaluating-logistic-regression-with-cross-validation
from sklearn.linear_model import LogisticRegression
from sklearn import metrics, model_selection
from sklearn import datasets

In [63]:
predicted = model_selection.cross_val_predict(LogisticRegression(), X, y.iloc[:,1], cv=10, method='predict')
print (1-metrics.accuracy_score(y.iloc[:,1], predicted))
print (metrics.classification_report(y.iloc[:,1], predicted))

0.03369999999999995
             precision    recall  f1-score   support

        0.0       0.97      1.00      0.98      9667
        1.0       0.00      0.00      0.00       333

avg / total       0.93      0.97      0.95     10000

In [64]:
predicted

array([0., 0., 0., ..., 0., 0., 0.])

## Question (e)

In [65]:
predicted = model_selection.cross_val_predict(LogisticRegression(), X, y.iloc[:,1], cv=10, method='predict_proba')

In [66]:
predict_label = pd.DataFrame(np.zeros(shape=(10000,1)), columns = ['label'])
predict_label.iloc[predicted[:,1]>0.2] = 1

In [67]:
print (1-metrics.accuracy_score(y.iloc[:,1], predict_label))
print (metrics.classification_report(y.iloc[:,1], predict_label))

0.08999999999999997
             precision    recall  f1-score   support

        0.0       0.97      0.94      0.95      9667
        1.0       0.07      0.14      0.10       333

avg / total       0.94      0.91      0.92     10000

In [68]:
predicted

array([[9.95245253e-01, 4.75474705e-03],
       [7.66280521e-01, 2.33719479e-01],
       [9.73015944e-01, 2.69840561e-02],
       ...,
       [9.99188675e-01, 8.11325078e-04],
       [9.81962928e-01, 1.80370716e-02],
       [8.87439944e-01, 1.12560056e-01]])

When the posterior probability is greater than 0.2, overal performance descreased. But it helped to detect more default cases than the model in (d).